name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # フォルダ構造を確認して適切な場所で npm install と build を実行する
      - name: Install and Build
        run: |
          if [ -f "./package.json" ]; then
            echo "Building from root directory..."
            npm install
            npm run build
          else
            SUBDIR=$(dirname $(find . -maxdepth 2 -name "package.json" | head -n 1))
            echo "Found package.json in $SUBDIR. Building inside subfolder..."
            cd "$SUBDIR"
            npm install
            npm run build
            mv out ../out
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
